// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4S5NWS9xHqr9wP_bAUdHo5ZRy1Q-552Q',
    appId: '1:894283317028:web:223bd25ee37f973d613db1',
    messagingSenderId: '894283317028',
    projectId: 'fir-authentication-41537',
    authDomain: 'fir-authentication-41537.firebaseapp.com',
    databaseURL: 'https://fir-authentication-41537-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-41537.appspot.com',
    measurementId: 'G-YCCDRHNSSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt5Obspdx84EBukfSoqbvvEjJ3ePVkU_4',
    appId: '1:894283317028:android:92bef6a529c72002613db1',
    messagingSenderId: '894283317028',
    projectId: 'fir-authentication-41537',
    databaseURL: 'https://fir-authentication-41537-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-41537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEHPJ5_PJkGtc0ANDUD_d-Nw3-eq5FlsQ',
    appId: '1:894283317028:ios:2b68298027f61308613db1',
    messagingSenderId: '894283317028',
    projectId: 'fir-authentication-41537',
    databaseURL: 'https://fir-authentication-41537-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-41537.appspot.com',
    androidClientId: '894283317028-v2nekgbdj1d9bv06ti0u12ilihn4gl60.apps.googleusercontent.com',
    iosClientId: '894283317028-5hvr9ujb3og7t22pomvi0u58of7jo5pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEHPJ5_PJkGtc0ANDUD_d-Nw3-eq5FlsQ',
    appId: '1:894283317028:ios:64e018fd5f33adbe613db1',
    messagingSenderId: '894283317028',
    projectId: 'fir-authentication-41537',
    databaseURL: 'https://fir-authentication-41537-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-41537.appspot.com',
    androidClientId: '894283317028-v2nekgbdj1d9bv06ti0u12ilihn4gl60.apps.googleusercontent.com',
    iosClientId: '894283317028-0rs4s3911fq6b1hstksdikt2rapr7p4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
